/* ══════════════════════════════════════════════════
   PARTNERSHIPS CALL ANALYSIS — Q3 2026
   Team: Jara · Nicola · Ezer · Aurel · Alex · Markus · Niels · Fred · Mees · Deniz
   Updated: Aug 04, 2026 — Full range Jun 1–Jul 31 (105/155 historical criteria scored)
   ══════════════════════════════════════════════════ */

const NOTION_PAGES = {
  jara:   "3821de46-2c03-81d0-be79-e9365e85a064",
  nicola: "3821de46-2c03-81c6-918e-f7eff9898bee",
  ezer:   "3821de46-2c03-818c-9f9d-ffba807edd45",
  aurel:  "3821de46-2c03-815e-a9b6-ec9c4cc8fbe5",
  alex:   "3821de46-2c03-81f6-aafa-dcae38d605da",
  markus: "3821de46-2c03-8126-9ad6-cafb79363f80",
  niels:  "3821de46-2c03-818f-9da0-d6829aad5338",
  fred:   "3961de46-2c03-81ef-837b-f47f84ff9f61",
  mees:   "3961de46-2c03-8114-8e85-e36a65c05f65",
  deniz:  null,
  taz:    "3821de46-2c03-8117-b122-e66e478fe728",
};

const REPS = ["Jara","Nicola","Ezer","Aurel","Alex","Markus","Niels","Fred","Mees","Deniz"];

/* ── ROLLING AVERAGES (Q3 — week by week) ──
   Each entry: { week, rep, Sourcing, Discovery, Demo, Checkin, PipelineReview, ProductEnablement, QBR }
   null = no scored calls that week for that type */
const REP_AVGS = [
  { week:"Jul 21", rep:"Jara",   Sourcing:null, Discovery:2.5, Demo:null, Checkin:null, PipelineReview:null, ProductEnablement:3.0, QBR:null },
  { week:"Jul 21", rep:"Nicola", Sourcing:null, Discovery:null, Demo:3.0, Checkin:2.0, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 21", rep:"Ezer",   Sourcing:2.0,  Discovery:2.8, Demo:null, Checkin:4.0, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 21", rep:"Aurel",  Sourcing:3.0,  Discovery:3.5, Demo:3.5, Checkin:null, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 21", rep:"Alex",   Sourcing:1.6,  Discovery:4.0, Demo:4.0, Checkin:null, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 21", rep:"Niels",  Sourcing:2.2,  Discovery:2.2, Demo:3.7, Checkin:2.5, PipelineReview:4.0, ProductEnablement:4.0, QBR:null },
  { week:"Jul 21", rep:"Fred",   Sourcing:2.0,  Discovery:null, Demo:2.0, Checkin:4.0, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 21", rep:"Deniz",  Sourcing:2.5,  Discovery:3.0, Demo:null, Checkin:3.0, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 21", rep:"Mees",   Sourcing:null, Discovery:null, Demo:null, Checkin:null, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 21", rep:"Markus", Sourcing:null, Discovery:null, Demo:null, Checkin:null, PipelineReview:null, ProductEnablement:null, QBR:null },
  // ── Week 2: Jul 28 ──
  { week:"Jul 28", rep:"Jara",   Sourcing:null, Discovery:3.5, Demo:3.0, Checkin:3.2, PipelineReview:3.0, ProductEnablement:3.5, QBR:null },
  { week:"Jul 28", rep:"Nicola", Sourcing:3.0,  Discovery:null, Demo:3.0, Checkin:2.0, PipelineReview:4.0, ProductEnablement:4.0, QBR:null },
  { week:"Jul 28", rep:"Ezer",   Sourcing:2.2,  Discovery:null, Demo:null, Checkin:4.0, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 28", rep:"Aurel",  Sourcing:2.7,  Discovery:3.5, Demo:3.0, Checkin:null, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 28", rep:"Alex",   Sourcing:1.3,  Discovery:3.5, Demo:3.0, Checkin:null, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 28", rep:"Niels",  Sourcing:2.0,  Discovery:2.0, Demo:null, Checkin:3.3, PipelineReview:3.0, ProductEnablement:3.7, QBR:null },
  { week:"Jul 28", rep:"Fred",   Sourcing:1.5,  Discovery:null, Demo:null, Checkin:null, PipelineReview:null, ProductEnablement:4.0, QBR:null },
  { week:"Jul 28", rep:"Deniz",  Sourcing:2.0,  Discovery:null, Demo:null, Checkin:3.0, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 28", rep:"Mees",   Sourcing:null, Discovery:null, Demo:null, Checkin:null, PipelineReview:null, ProductEnablement:null, QBR:null },
  { week:"Jul 28", rep:"Markus", Sourcing:null, Discovery:null, Demo:null, Checkin:null, PipelineReview:null, ProductEnablement:null, QBR:null },
];

/* ══ SOURCING — new criteria: O·R·Q·VP·OBJ·MTG ══
   O=Opening&relevance(w2) R=Research(w3) Q=Qualification(w3)
   VP=ValueProp(w2) OBJ=ObjectionHandling(w2,null=N/A) MTG=MeetingBooked(w3)
   HO=HandoverQuality(w2,null=N/A, only PA calls) */
/* ══ HISTORICAL SCORED CALLS (May 15–Jul 20) ══ */
const HISTORICAL_SOURCING = [
  {id:"cda9cf49",title:"Kevin Hütter",rep:"Deniz",date:"2026-07-20",score:1,outcome:"scored",criteria:[2,1,1,1],avg:1},
  {id:"9a85a6f5",title:"Tim Dillenberger",rep:"Deniz",date:"2026-07-20",score:1,outcome:"scored",criteria:[2,1,1,1],avg:1},
  {id:"1dad8a8c",title:"Thomas Bathon",rep:"Deniz",date:"2026-07-20",score:2,outcome:"scored",criteria:[2,1,3,1],avg:2},
  {id:"b072f876",title:"Peter Toutenhoofd",rep:"Niels",date:"2026-07-20",score:3,outcome:"scored",criteria:[3,1,3,5],avg:3},
  {id:"860cc8ba",title:"Charlie Shaw",rep:"Alex",date:"2026-07-20",score:2,outcome:"scored",criteria:[2,3,3,1],avg:2},
  {id:"e52b2241",title:"Pamela Duran",rep:"Ezer",date:"2026-07-17",score:2,outcome:"scored",criteria:[2,3,3,1],avg:2},
  {id:"c84bc82f",title:"Mustafa Ersalan",rep:"Ezer",date:"2026-07-17",score:2,outcome:"scored",criteria:[3,1,3,1],avg:2},
  {id:"f9f7780c",title:"Kamlesh Taili",rep:"Ezer",date:"2026-07-17",score:3,outcome:"scored",criteria:[2,4,3,4],avg:3},
  {id:"0478b0bc",title:"Ben n.a.",rep:"Ezer",date:"2026-07-17",score:1,outcome:"scored",criteria:[2,1,1,1],avg:1},
  {id:"fac6399e",title:"Karen Garrattley",rep:"Ezer",date:"2026-07-17",score:3,outcome:"scored",criteria:[2,4,4,1],avg:3},
  {id:"e3632751",title:"Aly Dewji",rep:"Ezer",date:"2026-07-17",score:2,outcome:"scored",criteria:[2,3,2,1],avg:2},
  {id:"7b06cd70",title:"Theo Kontos",rep:"Ezer",date:"2026-07-16",score:4,outcome:"scored",criteria:[3,4,3,5],avg:4},
  {id:"c250055b",title:"Andreas Baumann",rep:"Aurel",date:"2026-07-16",score:2,outcome:"scored",criteria:[2,3,3,1],avg:2},
  {id:"d468be3e",title:"Yevgeniy Boyko",rep:"Ezer",date:"2026-07-16",score:2,outcome:"scored",criteria:[2,1,3,3],avg:2},
  {id:"d17f8c0d",title:"Aly Dewji VM",rep:"Ezer",date:"2026-07-16",score:2,outcome:"scored",criteria:[4,1,3,1],avg:2},
  {id:"32e27c06",title:"Tai Daly",rep:"Ezer",date:"2026-07-16",score:3,outcome:"scored",criteria:[4,1,4,3],avg:3},
  {id:"1ea06a6a",title:"Paul Handscombe",rep:"Ezer",date:"2026-07-16",score:2,outcome:"scored",criteria:[3,1,3,1],avg:2},
  {id:"44b5bbe3",title:"Christian Schuller",rep:"Aurel",date:"2026-07-14",score:2,outcome:"scored",criteria:[3,1,3,3],avg:2},
  {id:"157541b4",title:"Max Allgower",rep:"Aurel",date:"2026-07-14",score:2,outcome:"scored",criteria:[3,1,3,3],avg:2},
  {id:"0cb879d4",title:"Reinier Mudde Sourcing",rep:"Niels",date:"2026-07-07",score:4,outcome:"scored",criteria:[3,4,3,1,5,0],avg:3},
  {id:"b2f8f0e7",title:"Ryan Wakeman",rep:"Ezer",date:"2026-07-03",score:3,outcome:"scored",criteria:[2,3,3,0,3,0],avg:2},
  {id:"311012bb",title:"Antoon Rakke",rep:"Niels",date:"2026-07-03",score:3,outcome:"scored",criteria:[4,1,3,0,3,0],avg:2},
  {id:"192f02ca",title:"Robin Wallaart",rep:"Niels",date:"2026-07-03",score:3,outcome:"scored",criteria:[4,1,3,0,5,0],avg:3},
  {id:"d511ff8c",title:"Luke Quince",rep:"Ezer",date:"2026-06-23",score:2,outcome:"scored",criteria:[4,1,3,1,0,0],avg:2},
  {id:"7b006a7d",title:"Chris Hession",rep:"Ezer",date:"2026-06-23",score:2,outcome:"scored",criteria:[4,1,3,1,0,0],avg:2},
  {id:"b6fb2560",title:"Morlai Kargbo",rep:"Ezer",date:"2026-06-23",score:2,outcome:"scored",criteria:[4,1,3,1,0,0],avg:2},
  {id:"7240fd8b",title:"Chris Barnard",rep:"Ezer",date:"2026-06-23",score:2,outcome:"scored",criteria:[3,1,3,0,3,0],avg:2},
  {id:"cc75caa9",title:"Flora Scholz",rep:"Aurel",date:"2026-06-23",score:3,outcome:"scored",criteria:[3,4,3,0,3,0],avg:2},
  {id:"9633cf3e",title:"Micky Johal",rep:"Alex",date:"2026-06-23",score:3,outcome:"scored",criteria:[3,4,3,0,1,0],avg:2},
  {id:"3910f384",title:"Sacheen",rep:"Alex",date:"2026-06-19",score:2,outcome:"scored",criteria:[3,3,3,0,1,0],avg:2},
  {id:"3e677f66",title:"Ruben Faust Sourcing",rep:"Aurel",date:"2026-06-19",score:4,outcome:"scored",criteria:[4,2,3,0,5,0],avg:3},
  {id:"6bcf0f04",title:"Scott McInnes",rep:"Ezer",date:"2026-06-18",score:4,outcome:"scored",criteria:[4,4,3,0,5,0],avg:3},
  {id:"9e736917",title:"Gary Bell",rep:"Alex",date:"2026-06-18",score:2,outcome:"scored",criteria:[2,3,3,0,1,0],avg:2},
  {id:"e80d1bdc",title:"Arun Shibu",rep:"Ezer",date:"2026-06-18",score:2,outcome:"scored",criteria:[2,2,2,0,1,0],avg:1},
  {id:"962466ce",title:"Glyn Jelley",rep:"Ezer",date:"2026-06-17",score:2,outcome:"scored",criteria:[4,1,3,0,1,0],avg:2},
  {id:"c5484dd1",title:"SLM",rep:"Alex",date:"2026-06-17",score:2,outcome:"scored",criteria:[1,1,3,0,3,0],avg:2},
  {id:"89b51832",title:"Michaela Randall",rep:"Alex",date:"2026-06-16",score:2,outcome:"scored",criteria:[2,1,3,0,4,0],avg:2},
  {id:"e9ad0e9b",title:"Hiral Shah",rep:"Ezer",date:"2026-06-16",score:1,outcome:"scored",criteria:[1,1,1,0,1,0],avg:1},
  {id:"d0dbd764",title:"Predrag Nikic",rep:"Ezer",date:"2026-06-15",score:2,outcome:"scored",criteria:[2,1,3,0,1,0],avg:1},
  {id:"232c8af7",title:"Rob Howard VM",rep:"Ezer",date:"2026-06-15",score:2,outcome:"scored",criteria:[4,1,3,0,1,0],avg:2},
  {id:"5aa5b5f1",title:"Alexander Schafer",rep:"Aurel",date:"2026-06-15",score:1,outcome:"scored",criteria:[1,1,3,0,1,0],avg:1},
  {id:"bdd4adf9",title:"Andrew Gibbs",rep:"Ezer",date:"2026-06-15",score:2,outcome:"scored",criteria:[2,1,3,0,1,0],avg:2},
  {id:"061117dc",title:"Peter Connon",rep:"Ezer",date:"2026-06-12",score:2,outcome:"scored",criteria:[2,2,1,0,1,0],avg:2},
  {id:"376b0885",title:"Voicemail Jun12",rep:"Ezer",date:"2026-06-12",score:2,outcome:"scored",criteria:[3,3,1,0,1,0],avg:2},
  {id:"26913e94",title:"Ryan Harris SANSA",rep:"Jara",date:"2026-06-12",score:2,outcome:"scored",criteria:[1,1,3,0,3,0],avg:2},
  {id:"ccb4921d",title:"Wes Rashid",rep:"Ezer",date:"2026-06-11",score:2,outcome:"scored",criteria:[2,1,3,0,1,0],avg:2},
  {id:"158fe315",title:"Wussler Schmid",rep:"Nicola",date:"2026-06-08",score:2,outcome:"scored",criteria:[2,1,2,0,1,0],avg:2},
  {id:"b4483a5f",title:"APA Sourcing",rep:"Ezer",date:"2026-06-08",score:3,outcome:"scored",criteria:[2,2,4,0,4,5],avg:3},
  {id:"94e7ec50",title:"Naman Gupta",rep:"Alex",date:"2026-06-05",score:1,outcome:"scored",criteria:[1,1,1,0,1,0],avg:1},
  {id:"98f5caeb",title:"Ronnie Patel",rep:"Ezer",date:"2026-06-05",score:1,outcome:"scored",criteria:[1,1,1,0,3,0],avg:1},
  {id:"30140dd5",title:"Ralf Meisel",rep:"Nicola",date:"2026-06-05",score:1,outcome:"scored",criteria:[1,1,1,0,3,0],avg:1},
  {id:"c10c9f00",title:"Rina Trivedi",rep:"Alex",date:"2026-06-05",score:1,outcome:"scored",criteria:[1,1,1,0,1,0],avg:1},
  {id:"707fc72a",title:"Chris Barker",rep:"Ezer",date:"2026-06-01",score:1,outcome:"scored",criteria:[1,1,1,0,1,0],avg:1},
  {id:"af703c41",title:"Aalia Rangrez",rep:"Ezer",date:"2026-06-01",score:1,outcome:"scored",criteria:[2,1,3,0,1,0],avg:1},
  {id:"7b9f01fd",title:"Ramona Oana",rep:"Alex",date:"2026-05-27",score:3,outcome:"scored"},
  {id:"a2526751",title:"Jan Dittmann",rep:"Aurel",date:"2026-05-26",score:1,outcome:"scored"},
  {id:"c7cef3ea",title:"Oliver Breitfeld",rep:"Aurel",date:"2026-05-26",score:2,outcome:"scored"},
  {id:"76eafa85",title:"Thomas Kersting",rep:"Aurel",date:"2026-05-21",score:2,outcome:"scored"},
  {id:"8034f927",title:"Nico Doehrn Sourcing",rep:"Aurel",date:"2026-05-22",score:3,outcome:"scored"},
  {id:"50030f10",title:"Corine Denekamp",rep:"Niels",date:"2026-05-19",score:4,outcome:"scored"},
  {id:"bf4bc39f",title:"Lenthe Steeman",rep:"Niels",date:"2026-05-18",score:2,outcome:"scored"},
  {id:"179d4010",title:"Cindy Beckel",rep:"Jara",date:"2026-05-28",score:2,outcome:"scored"},
  {id:"2446c770",title:"Ines Harmuth",rep:"Markus",date:"2026-05-28",score:3,outcome:"scored"},
];

const HISTORICAL_DISCOVERY = [
  {id:"5cbbbe50",title:"Roeland van Luijk",rep:"Niels",date:"2026-07-20",path:"pm_direct",score:2,outcome:"scored",criteria:[3,1,3,1,1,2],avg:2},
  {id:"4fbf3717",title:"Nathan Holmes",rep:"Ezer",date:"2026-07-20",path:"pm_direct",score:2,outcome:"scored",criteria:[4,1,1,1,3,2],avg:2},
  {id:"40805fbd",title:"Akos Balogh pre",rep:"Ezer",date:"2026-07-20",path:"pm_direct",score:1,outcome:"scored",criteria:[1,1,1,1,3,1],avg:1},
  {id:"4ff37596",title:"Chriss Goodey",rep:"Ezer",date:"2026-07-20",path:"pm_direct",score:2,outcome:"scored",criteria:[2,1,1,3,5,2],avg:2},
  {id:"cb32afa6",title:"Bytes Software",rep:"Ezer",date:"2026-07-17",path:"pm_direct",score:3,outcome:"scored",criteria:[3,1,2,4,3,2],avg:3},
  {id:"ffedc2e9",title:"FD Works",rep:"Jara",date:"2026-07-17",path:"pm_direct",score:3,outcome:"scored",criteria:[4,1,2,3,5,4],avg:3},
  {id:"a330fbc1",title:"Borgo IE",rep:"Jara",date:"2026-07-16",path:"pm_direct",score:3,outcome:"scored",criteria:[2,1,1,5,5,3],avg:3},
  {id:"95a122da",title:"Nico Straub",rep:"Deniz",date:"2026-07-16",path:"pm_direct",score:2,outcome:"scored",criteria:[1,1,1,1,5,2],avg:2},
  {id:"6291741e",title:"Frank de Vries FYBE",rep:"Niels",date:"2026-07-15",path:"pm_direct",score:3,outcome:"scored",criteria:[1,1,1,4,5,3],avg:3},
  {id:"d9d79d58",title:"Akos Balogh FYBE",rep:"Ezer",date:"2026-07-15",path:"pm_direct",score:2,outcome:"scored",criteria:[2,5,1,1,5,2],avg:2},
  {id:"4c3f8f3e",title:"Mark Van De Beek",rep:"Niels",date:"2026-07-14",path:"pm_direct",score:3,outcome:"scored",criteria:[3,1,1,5,3,2],avg:3},
  {id:"74550b50",title:"KPMG Austria",rep:"Aurel",date:"2026-07-14",path:"pm_direct",score:2,outcome:"scored",criteria:[3,1,1,1,4,2],avg:2},
  {id:"9f8a834a",title:"Mark Oudeavenhuis FYBE",rep:"Niels",date:"2026-07-14",path:"pm_direct",score:2,outcome:"scored",criteria:[3,1,1,1,5,5],avg:3},
  {id:"77138035",title:"Phil Benson Finance",rep:"Alex",date:"2026-07-13",path:"pm_direct",score:4,outcome:"scored",criteria:[4,3,5,3,3,3],avg:4},
  {id:"896742a4",title:"Steuerwehr",rep:"Aurel",date:"2026-07-13",path:"pm_direct",score:3,outcome:"scored",criteria:[4,1,1,1,5,5],avg:3},
  {id:"63cc3e5a",title:"Manthey Steuerberatung",rep:"Aurel",date:"2026-07-09",path:"pm_direct",score:2,outcome:"scored",criteria:[4,1,1,1,5,1],avg:2},
  {id:"965b8484",title:"Max Zeegers FYBE",rep:"Niels",date:"2026-07-09",path:"pm_direct",score:2,outcome:"scored",criteria:[3,3,1,1,3,4],avg:3},
  {id:"54c494aa",title:"Jeroen Glebbeek FYBE",rep:"Niels",date:"2026-07-08",path:"pm_direct",score:3,outcome:"scored",criteria:[2,2,3,1,4,4],avg:3},
  {id:"4abda7cb",title:"Milena De Coop",rep:"Niels",date:"2026-07-08",path:"pm_direct",score:2,outcome:"scored",criteria:[2,1,3,1,3,2],avg:2},
  {id:"82f67532",title:"BDU Benedikt Ebert",rep:"Aurel",date:"2026-07-08",path:"pm_direct",score:3,outcome:"scored",criteria:[4,1,3,1,5,2],avg:3},
  {id:"1636159c",title:"Lisa Schuler WTK",rep:"Aurel",date:"2026-07-08",path:"pm_direct",score:3,outcome:"scored",criteria:[4,1,1,5,5,4],avg:3},
  {id:"954edd51",title:"Eleonore De Ridder",rep:"Aurel",date:"2026-07-07",path:"pm_direct",score:1,outcome:"scored",criteria:[1,1,1,1,3,2],avg:2},
  {id:"071ed535",title:"DDA Fenna",rep:"Niels",date:"2026-07-07",path:"pm_direct",score:1,outcome:"scored",criteria:[1,1,1,1,3,2],avg:2},
  {id:"56bd827f",title:"Kock Hellmold",rep:"Aurel",date:"2026-07-07",path:"pm_direct",score:3,outcome:"scored",criteria:[4,1,1,1,5,4],avg:3},
  {id:"5d5ff866",title:"Ishant Sharma",rep:"Ezer",date:"2026-07-06",path:"pm_direct",score:3,outcome:"scored",criteria:[1,3,4,4,3,2],avg:3},
  {id:"48af2c02",title:"Franz Salzmann",rep:"Nicola",date:"2026-07-03",path:"pm_direct",score:2,outcome:"scored",criteria:[1,1,3,3,3,2],avg:2},
  {id:"8b6d2834",title:"Arran Turner",rep:"Ezer",date:"2026-06-23",path:"pm_direct",score:2,outcome:"scored",criteria:[2,1,2,1,5,2],avg:2},
  {id:"4f232c19",title:"Ruben Faust Discovery",rep:"Aurel",date:"2026-06-23",path:"pm_direct",score:4,outcome:"scored",criteria:[4,3,2,5,3,5],avg:4},
  {id:"49afbc16",title:"Limetax",rep:"Nicola",date:"2026-06-22",path:"pm_direct",score:3,outcome:"scored",criteria:[4,3,3,1,3,2],avg:3},
  {id:"e7eaf313",title:"Timo Daedrich",rep:"Aurel",date:"2026-06-22",path:"pm_direct",score:3,outcome:"scored",criteria:[5,4,2,4,3,3],avg:4},
  {id:"acad05c5",title:"Torsten Mayer Sourcing",rep:"Aurel",date:"2026-06-19",path:"pm_direct",score:2,outcome:"scored",criteria:[2,2,2,1,4,0],avg:2},
  {id:"e73032d3",title:"Benjamin Pasqualino Discovery",rep:"Aurel",date:"2026-06-19",path:"pm_direct",score:2,outcome:"scored",criteria:[1,1,2,1,4,0],avg:2},
  {id:"be44f54c",title:"Bart Lammers",rep:"Niels",date:"2026-06-18",path:"pm_direct",score:2,outcome:"scored",criteria:[2,2,2,1,3,0],avg:2},
  {id:"477ce1a3",title:"Iscoseles Finance",rep:"Alex",date:"2026-06-18",path:"pm_direct",score:4,outcome:"scored",criteria:[4,4,3,4,3,0],avg:4},
  {id:"e19a2f98",title:"Xeinadin",rep:"Jara",date:"2026-06-18",path:"pm_direct",score:2,outcome:"scored",criteria:[2,2,3,1,3,0],avg:2},
  {id:"024b84a7",title:"Fintua",rep:"Alex",date:"2026-06-18",path:"pm_direct",score:3,outcome:"scored",criteria:[4,2,2,4,3,0],avg:3},
  {id:"469017ef",title:"Eelco Houwert",rep:"Niels",date:"2026-06-17",path:"pm_direct",score:2,outcome:"scored",criteria:[2,2,3,1,3,0],avg:2},
  {id:"0771e0a2",title:"IG Immobilien",rep:"Aurel",date:"2026-06-16",path:"pm_direct",score:2,outcome:"scored",criteria:[1,1,2,3,5,0],avg:2},
  {id:"d21331a9",title:"Philip Humphries",rep:"Ezer",date:"2026-06-16",path:"pm_direct",score:2,outcome:"scored",criteria:[2,3,3,1,3,0],avg:2},
  {id:"d555fbad",title:"Jonathan Carling",rep:"Ezer",date:"2026-06-15",path:"pm_direct",score:2,outcome:"scored",criteria:[4,1,1,1,3,0],avg:2},
  {id:"e46d285e",title:"Rob Howard",rep:"Ezer",date:"2026-06-15",path:"pm_direct",score:3,outcome:"scored"},
  {id:"99f06ced",title:"Rahul Panday",rep:"Alex",date:"2026-06-15",path:"pm_direct",score:2,outcome:"scored"},
  {id:"5a0b0acf",title:"Sam n.a.",rep:"Ezer",date:"2026-06-15",path:"pm_direct",score:2,outcome:"scored"},
  {id:"45dc6fcd",title:"Lauren MacIver",rep:"Ezer",date:"2026-06-15",path:"pm_direct",score:2,outcome:"scored"},
  {id:"a0462026",title:"Game Discovery",rep:"Markus",date:"2026-06-15",path:"pm_direct",score:3,outcome:"scored"},
  {id:"43821907",title:"Chris Chan",rep:"Ezer",date:"2026-06-12",path:"pm_direct",score:2,outcome:"scored"},
  {id:"ffd6d898",title:"Lucy Cardew",rep:"Ezer",date:"2026-06-12",path:"pm_direct",score:3,outcome:"scored"},
  {id:"6a4721b9",title:"Justis Vercoe",rep:"Ezer",date:"2026-06-11",path:"pm_direct",score:2,outcome:"scored"},
  {id:"623f9acd",title:"CCA Discovery",rep:"Jara",date:"2026-06-09",path:"pm_direct",score:2,outcome:"scored"},
  {id:"63e1889f",title:"Stephan Grad Discovery",rep:"Aurel",date:"2026-06-09",path:"pm_direct",score:4,outcome:"scored"},
  {id:"1da166ea",title:"Argus Search",rep:"Nicola",date:"2026-06-09",path:"pm_direct",score:4,outcome:"scored"},
  {id:"7cb3c91d",title:"Bitesize Discovery",rep:"Jara",date:"2026-06-08",path:"pm_direct",score:2,outcome:"scored"},
  {id:"fb5451d4",title:"Bizaway",rep:"Jara",date:"2026-06-04",path:"pm_direct",score:2,outcome:"scored"},
  {id:"2bae4a59",title:"IBB Ventures",rep:"Jara",date:"2026-06-03",path:"pm_direct",score:4,outcome:"scored"},
  {id:"f3a3d903",title:"Ideas Community",rep:"Alex",date:"2026-06-03",path:"pm_direct",score:2,outcome:"scored"},
  {id:"5ec5fde2",title:"Miro Schmiedt",rep:"Nicola",date:"2026-06-02",path:"pm_direct",score:3,outcome:"scored"},
  {id:"b20995a7",title:"Patrick Schreiner",rep:"Nicola",date:"2026-06-01",path:"pm_direct",score:2,outcome:"scored"},
];

const HISTORICAL_DEMO = [
  {id:"c58b78cb",title:"FYBE Tiffany Demo",rep:"Niels",date:"2026-07-17",score:4,outcome:"scored",criteria:[4,3,3,3,4,4],avg:4},
  {id:"cd98aea0",title:"Akos Balogh Demo",rep:"Alex",date:"2026-07-17",score:4,outcome:"scored",criteria:[1,4,3,4,5,5],avg:4},
  {id:"d6342168",title:"Lisa Schuler Demo",rep:"Aurel",date:"2026-07-17",score:3,outcome:"scored",criteria:[2,4,2,3,4,4],avg:3},
  {id:"b0132171",title:"Williams Stanley",rep:"Jara",date:"2026-07-16",score:2,outcome:"scored",criteria:[3,2,2,1,2,2],avg:2},
  {id:"abfbab97",title:"Reinier Mudde FYBE 1",rep:"Niels",date:"2026-07-15",score:4,outcome:"scored",criteria:[4,4,3,3,4,3],avg:4},
  {id:"e2cc9884",title:"Sempar Demo",rep:"Alex",date:"2026-07-15",score:3,outcome:"scored",criteria:[4,4,3,4,3,2],avg:3},
  {id:"acc75cab",title:"Reinier Mudde FYBE 2",rep:"Niels",date:"2026-07-14",score:4,outcome:"scored",criteria:[4,4,4,3,4,4],avg:4},
  {id:"d372c1ed",title:"Alex Kock Demo",rep:"Aurel",date:"2026-07-14",score:3,outcome:"scored",criteria:[4,4,2,3,4,4],avg:4},
  {id:"e7489baf",title:"Kitty Veenema FYBE",rep:"Niels",date:"2026-07-08",score:3,outcome:"scored",criteria:[3,3,2,3,4,4],avg:3},
  {id:"bdff38d9",title:"Ewout Bastiaannet FYBE",rep:"Niels",date:"2026-07-08",score:3,outcome:"scored",criteria:[4,4,2,2,4,4],avg:3},
  {id:"2f7f4408",title:"Alain Wickenhagen FYBE",rep:"Niels",date:"2026-07-08",score:2,outcome:"scored",criteria:[2,3,2,2,4,4],avg:3},
  {id:"cdae8156",title:"De Coop Demo",rep:"Niels",date:"2026-06-23",score:3,outcome:"scored",criteria:[4,4,4,3,2,3],avg:3},
  {id:"6403c282",title:"Torsten Mayer Demo",rep:"Aurel",date:"2026-06-22",score:3,outcome:"scored",criteria:[2,3,3,0,3,4],avg:3},
  {id:"9219c80c",title:"Benjamin Pasqualino Demo",rep:"Aurel",date:"2026-06-22",score:4,outcome:"scored",criteria:[4,4,4,0,3,3],avg:4},
  {id:"92d0e4f6",title:"AMICON Demo",rep:"Nicola",date:"2026-06-22",score:3,outcome:"scored",criteria:[4,4,4,2,3,3],avg:3},
  {id:"49243817",title:"Ali Nada Demo",rep:"Aurel",date:"2026-06-19",score:3,outcome:"scored",criteria:[2,3,2,0,3,3],avg:3},
  {id:"0e3b3870",title:"APA Demo",rep:"Alex",date:"2026-06-19",score:2,outcome:"scored",criteria:[3,3,2,0,1,0],avg:2},
  {id:"712b2c24",title:"Modjo Zandbergen",rep:"Niels",date:"2026-06-19",score:4,outcome:"scored",criteria:[4,4,3,0,5,4],avg:3},
  {id:"14ece3ea",title:"Barry De Coop Demo",rep:"Niels",date:"2026-06-18",score:3,outcome:"scored",criteria:[3,3,3,0,4,0],avg:3},
  {id:"1a13cb89",title:"OFSGroep Demo",rep:"Niels",date:"2026-06-18",score:4,outcome:"scored",criteria:[4,4,4,0,3,0],avg:3},
  {id:"724adb25",title:"Accountability Demo",rep:"Ezer",date:"2026-06-17",score:3,outcome:"scored",criteria:[4,3,3,0,1,0],avg:2},
  {id:"14e7a961",title:"PwC Elvera",rep:"Niels",date:"2026-06-17",score:4,outcome:"scored",criteria:[5,5,4,0,3,0],avg:4},
  {id:"6d75673e",title:"Catalyst Demo v1",rep:"Jara",date:"2026-06-16",score:2,outcome:"scored",criteria:[2,1,2,0,4,0],avg:2},
  {id:"20f3aed2",title:"Catalyst Demo v2",rep:"Jara",date:"2026-06-16",score:4,outcome:"scored",criteria:[4,5,2,0,3,0],avg:3},
  {id:"a934d6e0",title:"Nico Doehrn Demo",rep:"Aurel",date:"2026-06-16",score:4,outcome:"scored",criteria:[3,4,5,0,5,0],avg:4},
  {id:"be76f9bd",title:"WWS Markus Demo",rep:"Markus",date:"2026-06-15",score:4,outcome:"scored",criteria:[4,4,3,0,3,0],avg:3},
  {id:"92a1d8e4",title:"Moss Demo Jara",rep:"Jara",date:"2026-06-15",score:4,outcome:"scored",criteria:[3,4,4,0,3,0],avg:3},
  {id:"6d2d9cf5",title:"Carlos Trejo Demo",rep:"Aurel",date:"2026-06-15",score:1,outcome:"scored",criteria:[1,1,1,0,1,0],avg:1},
  {id:"845f6b58",title:"EY Austria Demo",rep:"Aurel",date:"2026-06-11",score:4,outcome:"scored",criteria:[4,5,4,0,5,0],avg:4},
  {id:"98a9f569",title:"BT Consulting Demo",rep:"Aurel",date:"2026-06-11",score:4,outcome:"scored",criteria:[4,4,4,0,4,0],avg:4},
  {id:"2b36b46c",title:"AMT Demo",rep:"Alex",date:"2026-06-05",score:4,outcome:"scored",criteria:[4,4,4,0,3,0],avg:4},
  {id:"9b9d84ef",title:"Zedra Demo",rep:"Alex",date:"2026-06-04",score:2,outcome:"scored",criteria:[2,2,3,0,4,0],avg:2},
  {id:"fbeffaed",title:"Supy Demo",rep:"Jara",date:"2026-06-03",score:3,outcome:"scored",criteria:[4,3,3,0,3,0],avg:3},
];

const HISTORICAL_MANAGEMENT = [
  {id:"fa4be6ad",title:"Mick Weijers",rep:"Niels",date:"2026-07-17",subtype:"checkin",score:2,outcome:"scored"},
  {id:"d677dfda",title:"Sebastiaan Baas",rep:"Niels",date:"2026-07-17",subtype:"checkin",score:2,outcome:"scored"},
  {id:"8312790e",title:"Twigger Ezer",rep:"Ezer",date:"2026-07-07",subtype:"checkin",score:1,outcome:"scored"},
  {id:"a54bb929",title:"Greg Martin SANSA",rep:"Jara",date:"2026-06-23",subtype:"checkin",score:3,outcome:"scored"},
  {id:"1913bda9",title:"Knappworst",rep:"Nicola",date:"2026-06-22",subtype:"checkin",score:2,outcome:"scored"},
  {id:"985357c4",title:"Moss x Integral",rep:"Jara",date:"2026-06-22",subtype:"checkin",score:3,outcome:"scored"},
  {id:"6313751d",title:"Sil Teeken",rep:"Niels",date:"2026-06-22",subtype:"checkin",score:2,outcome:"scored"},
  {id:"b5aa690c",title:"Felix Schmitt",rep:"Nicola",date:"2026-06-22",subtype:"checkin",score:2,outcome:"scored"},
  {id:"16f8988c",title:"Ezer check-in",rep:"Ezer",date:"2026-06-15",subtype:"checkin",score:2,outcome:"scored"},
  {id:"ea93391b",title:"Ezer Management",rep:"Ezer",date:"2026-06-11",subtype:"checkin",score:2,outcome:"scored"},
  {id:"f739f651",title:"Laura Smith",rep:"Ezer",date:"2026-06-11",subtype:"checkin",score:1,outcome:"scored"},
];

const SOURCING = [
  {title:"Travus Wynne MAAT",rep:"Ezer",date:"2026-07-22",dur:"7m",O:4,R:4,Q:4,VP:4,OBJ:null,MTG:4,HO:null,score:4.0,outcome:"discovery_booked",well:"Strong opener referencing client base. All must-confirms covered. Meeting booked verbally.",wrong:"No firm objection arose — good. Research could have included something personal."},
  {title:"Frank Schmidt",rep:"Aurel",date:"2026-07-28",dur:"7m",O:3,R:3,Q:3,VP:3,OBJ:null,MTG:3,HO:null,score:3.0,outcome:"follow_up_agreed",well:"Relevant contact. Partnership relevance established. Follow-up agreed.",wrong:"Client base not fully confirmed. No specific date locked."},
  {title:"Martin Huber",rep:"Aurel",date:"2026-07-28",dur:"2m",O:3,R:3,Q:2,VP:2,OBJ:null,MTG:2,HO:null,score:2.6,outcome:"callback_agreed",well:"Contact made. Gatekeeper dynamic handled.",wrong:"Too short for meaningful qualification. No meeting booked."},
  {title:"Gerwin Koning",rep:"Niels",date:"2026-07-23",dur:"4m",O:3,R:3,Q:3,VP:3,OBJ:null,MTG:3,HO:null,score:3.0,outcome:"discovery_booked",well:"Accountant confirmed. Partnership relevance explained. Discovery booked.",wrong:"No personal research shown. Very short."},
  {title:"Gerwin Koning (sourcing)",rep:"Niels",date:"2026-07-23",dur:"4m",O:3,R:3,Q:2,VP:3,OBJ:null,MTG:2,HO:null,score:2.7,outcome:"follow_up_agreed",well:"First contact. Warm tone.",wrong:"Short. No qualification depth. No date."},
  {title:"Flora Scholz",rep:"Aurel",date:"2026-07-21",dur:"2m",O:3,R:3,Q:2,VP:3,OBJ:null,MTG:2,HO:null,score:2.6,outcome:"callback_agreed",well:"Relevant contact identified. Callback agreed.",wrong:"Too short. No qualification."},
  {title:"Svetlana Ryzhenko",rep:"Deniz",date:"2026-07-21",dur:"4m",O:3,R:3,Q:2,VP:3,OBJ:null,MTG:3,HO:null,score:2.8,outcome:"follow_up_agreed",well:"Warm call. Contact engaged. Follow-up agreed.",wrong:"Client base not confirmed. No date locked."},
  {title:"Thomas Buhl MBA",rep:"Deniz",date:"2026-07-21",dur:"4m",O:2,R:2,Q:2,VP:2,OBJ:null,MTG:2,HO:null,score:2.0,outcome:"follow_up_agreed",well:"Contact made.",wrong:"Generic. No research. No qualification. Vague follow-up."},
  {title:"Ali Ayoz",rep:"Niels",date:"2026-07-22",dur:"2m",O:3,R:3,Q:2,VP:3,OBJ:null,MTG:3,HO:null,score:2.8,outcome:"follow_up_agreed",well:"Accountant confirmed. Follow-up agreed.",wrong:"Very short. No qualification depth."},
  {title:"Dirk van den Bosch",rep:"Niels",date:"2026-07-22",dur:"1m",O:1,R:1,Q:1,VP:1,OBJ:null,MTG:1,HO:null,score:1.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"Under 2 min. No meaningful conversation."},
  {title:"John Hegney",rep:"Alex",date:"2026-07-22",dur:"9m",O:2,R:2,Q:2,VP:3,OBJ:null,MTG:3,HO:null,score:2.5,outcome:"follow_up_agreed",well:"Engaged conversation. Product area discussed.",wrong:"Wrong company referenced at start. Date confusion at close."},
  {title:"Bart De Smedt",rep:"Niels",date:"2026-07-22",dur:"2m",O:2,R:2,Q:2,VP:2,OBJ:null,MTG:2,HO:null,score:2.0,outcome:"follow_up_agreed",well:"Contact made.",wrong:"Too short. No qualification."},
  {title:"Holger Walter",rep:"Deniz",date:"2026-07-24",dur:"7m",O:3,R:3,Q:3,VP:3,OBJ:null,MTG:3,HO:null,score:3.0,outcome:"follow_up_agreed",well:"Good intro. Cards/invoicing context confirmed. Follow-up agreed.",wrong:"No specific date. No deep qualification."},
  {title:"Graham Cantlay",rep:"Alex",date:"2026-07-27",dur:"7m",O:2,R:2,Q:2,VP:2,OBJ:2,MTG:1,HO:null,score:2.0,outcome:"no_next_step",well:"Partner-type contact reached.",wrong:"Objection not handled. No next step."},
  {title:"Cerith Williams",rep:"Ezer",date:"2026-07-28",dur:"4m",O:2,R:1,Q:1,VP:2,OBJ:null,MTG:1,HO:null,score:1.5,outcome:"no_next_step",well:"Contact made.",wrong:"No research. No qualification. No next step."},
  {title:"Fred Sourcing (2a61812a)",rep:"Fred",date:"2026-07-27",dur:"7m",O:3,R:3,Q:2,VP:3,OBJ:null,MTG:3,HO:null,score:2.8,outcome:"follow_up_agreed",well:"Accounts payable context. Cards area confirmed. Follow-up agreed.",wrong:"No specific date. No qualification depth."},
  {title:"Hannah Roome",rep:"Fred",date:"2026-07-28",dur:"1m",O:1,R:1,Q:1,VP:1,OBJ:null,MTG:1,HO:null,score:1.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"Under 2 min. No substance."},
  {title:"Sarfraz Khan",rep:"Alex",date:"2026-07-22",dur:"4m",O:2,R:2,Q:2,VP:2,OBJ:null,MTG:2,HO:null,score:2.0,outcome:"no_next_step",well:"Accounting contact reached.",wrong:"Generic opener. No qualification. No next step."},
  {title:"Gunjan Shukla",rep:"Alex",date:"2026-07-22",dur:"4m",O:2,R:2,Q:2,VP:2,OBJ:null,MTG:2,HO:null,score:2.0,outcome:"no_next_step",well:"Accounting integrations mentioned.",wrong:"No research. No qualification. No next step."},
  {title:"Alan Purser",rep:"Ezer",date:"2026-07-27",dur:"3m",O:2,R:2,Q:2,VP:2,OBJ:null,MTG:2,HO:null,score:2.0,outcome:"follow_up_agreed",well:"Contact made. Accounts payable context.",wrong:"No research. No qualification. Vague follow-up."},
  {title:"Rachael Woosey",rep:"Ezer",date:"2026-07-27",dur:"2m",O:2,R:1,Q:1,VP:2,OBJ:null,MTG:1,HO:null,score:1.5,outcome:"no_next_step",well:"Contact made.",wrong:"No research. No qualification. No next step."},
  {title:"Jonathan Carr ACA",rep:"Ezer",date:"2026-07-28",dur:"2m",O:2,R:2,Q:1,VP:2,OBJ:null,MTG:1,HO:null,score:1.6,outcome:"no_next_step",well:"ACA contact — right profile.",wrong:"Gatekeeper dynamic. No DM reached. No next step."},
  {title:"Lisa Colwill",rep:"Ezer",date:"2026-07-28",dur:"2m",O:2,R:1,Q:1,VP:2,OBJ:null,MTG:1,HO:null,score:1.4,outcome:"no_next_step",well:"Contact made.",wrong:"No research. No qualification. No meeting."},
  // ── Week 2: Jul 28 ──
  {title:"Inez Buitenwerf",rep:"Niels",date:"2026-07-30",dur:"5m",O:2,R:2,Q:2,VP:2,OBJ:null,MTG:2,HO:null,score:2.0,outcome:"follow_up_agreed",well:"Accountant contact reached.",wrong:"Short. No qualification depth. No meeting booked."},
  {title:"Katinka den Braber",rep:"Niels",date:"2026-07-30",dur:"3m",O:2,R:2,Q:2,VP:2,OBJ:null,MTG:1,HO:null,score:2.0,outcome:"no_next_step",well:"Contact made.",wrong:"Too short. No qualification. No next step."},
  {title:"Martin Gugel",rep:"Nicola",date:"2026-07-30",dur:"5m",O:3,R:3,Q:2,VP:3,OBJ:null,MTG:3,HO:null,score:2.8,outcome:"follow_up_agreed",well:"Accounting contact. Relevant hook. Follow-up agreed.",wrong:"No client base confirmation. No date locked."},
  {title:"Joep van der Vliet",rep:"Niels",date:"2026-07-29",dur:"3m",O:3,R:3,Q:2,VP:3,OBJ:null,MTG:2,HO:null,score:2.6,outcome:"follow_up_agreed",well:"Contact made. Cards area confirmed.",wrong:"Short. No qualification. No date."},
  {title:"Joey Bont",rep:"Niels",date:"2026-07-29",dur:"3m",O:1,R:1,Q:1,VP:1,OBJ:null,MTG:1,HO:null,score:1.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"No research. No qualification. No next step."},
  {title:"Dennis Hilgefort",rep:"Deniz",date:"2026-07-29",dur:"3m",O:2,R:2,Q:2,VP:2,OBJ:null,MTG:2,HO:null,score:2.0,outcome:"follow_up_agreed",well:"Contact made.",wrong:"Short. No qualification depth."},
  {title:"Ronan Shally",rep:"Alex",date:"2026-07-29",dur:"1m",O:1,R:1,Q:1,VP:1,OBJ:null,MTG:1,HO:null,score:1.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"Under 1 min. No substance."},
  {title:"James Piper",rep:"Alex",date:"2026-07-29",dur:"1m",O:1,R:1,Q:1,VP:1,OBJ:null,MTG:1,HO:null,score:1.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"Under 1 min. No substance."},
  {title:"Nipun Gupta",rep:"Alex",date:"2026-07-29",dur:"1m",O:2,R:1,Q:1,VP:2,OBJ:null,MTG:2,HO:null,score:1.6,outcome:"no_next_step",well:"Accounting contact reached.",wrong:"Gatekeeper. No qualification. No next step."},
  {title:"Frank Schmidt",rep:"Aurel",date:"2026-07-28",dur:"7m",O:3,R:3,Q:3,VP:3,OBJ:null,MTG:3,HO:null,score:3.0,outcome:"follow_up_agreed",well:"Relevant contact. Partnership relevance confirmed.",wrong:"No specific date."},
  {title:"Martin Huber",rep:"Aurel",date:"2026-07-28",dur:"2m",O:3,R:2,Q:2,VP:2,OBJ:null,MTG:2,HO:null,score:2.4,outcome:"callback_agreed",well:"Contact made.",wrong:"Too short. Gatekeeper dynamic."},
  {title:"Christian Neidl",rep:"Aurel",date:"2026-07-28",dur:"4m",O:2,R:2,Q:2,VP:2,OBJ:null,MTG:2,HO:null,score:2.0,outcome:"no_next_step",well:"Accounting contact.",wrong:"Gatekeeper. No qualification. No next step."},
  {title:"Cerith Williams",rep:"Ezer",date:"2026-07-28",dur:"4m",O:2,R:1,Q:1,VP:2,OBJ:null,MTG:1,HO:null,score:1.5,outcome:"no_next_step",well:"Contact made.",wrong:"No research. No qualification. No next step."},
  {title:"Jonathan Carr ACA",rep:"Ezer",date:"2026-07-28",dur:"2m",O:2,R:2,Q:1,VP:2,OBJ:null,MTG:1,HO:null,score:1.6,outcome:"no_next_step",well:"ACA contact.",wrong:"Gatekeeper. No next step."},
  {title:"Lisa Colwill (W2)",rep:"Ezer",date:"2026-07-29",dur:"2m",O:2,R:1,Q:1,VP:2,OBJ:null,MTG:1,HO:null,score:1.4,outcome:"no_next_step",well:"Contact made.",wrong:"No research. No qualification. No next step."},
  {title:"Jean Freeman",rep:"Alex",date:"2026-07-28",dur:"1m",O:1,R:1,Q:1,VP:1,OBJ:null,MTG:1,HO:null,score:1.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"1 min. No substance."},
  {title:"Paul Norris",rep:"Alex",date:"2026-07-28",dur:"1m",O:2,R:1,Q:1,VP:1,OBJ:null,MTG:2,HO:null,score:1.4,outcome:"no_next_step",well:"Accounting firm reached.",wrong:"Gatekeeper. No conversation."},
  {title:"Chris Callow",rep:"Alex",date:"2026-07-28",dur:"1m",O:1,R:1,Q:1,VP:1,OBJ:null,MTG:1,HO:null,score:1.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"1 min. No substance."},
  {title:"Fred Sourcing A",rep:"Fred",date:"2026-07-28",dur:"5m",O:3,R:3,Q:2,VP:3,OBJ:null,MTG:3,HO:null,score:2.8,outcome:"follow_up_agreed",well:"Cards area confirmed. Follow-up agreed.",wrong:"No specific date. No qualification depth."},
  {title:"James Ripley",rep:"Fred",date:"2026-07-28",dur:"2m",O:1,R:1,Q:1,VP:1,OBJ:null,MTG:1,HO:null,score:1.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"Gatekeeper. No substance."},
  {title:"Charles Adams",rep:"Fred",date:"2026-07-28",dur:"2m",O:1,R:1,Q:1,VP:1,OBJ:null,MTG:1,HO:null,score:1.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"Gatekeeper. No substance."},
  {title:"Hannah Roome (W2)",rep:"Fred",date:"2026-07-28",dur:"1m",O:1,R:1,Q:1,VP:1,OBJ:null,MTG:1,HO:null,score:1.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"1 min. No substance."},
];

/* ══ DISCOVERY — new criteria: RAP·R·CB·ADM·CH·NS ══
   RAP=OpeningRapport(w2) R=Research(w2) CB=CustomerBaseQual(w3)
   ADM=AccessDecisionMoment(w3) CH=ChampionDM(w2) NS=NextStep(w3)
   path: "pa_handover" | "pm_direct" */
const DISCOVERY = [
  {title:"Tech Enable / Moss",rep:"Alex",date:"2026-07-28",dur:"25m",path:"pm_direct",RAP:4,R:4,CB:4,ADM:4,CH:4,NS:4,score:4.0,outcome:"follow_up_agreed",well:"Strong qualification. Gunjan engaged on integration use case. All must-confirms covered.",wrong:"Next step could have been a demo — stayed exploratory."},
  {title:"Heliad x Moss Partnership",rep:"Alex",date:"2026-07-24",dur:"35m",path:"pm_direct",RAP:4,R:4,CB:4,ADM:4,CH:4,NS:4,score:4.0,outcome:"follow_up_agreed",well:"Strong discovery. VC portfolio angle. Alex referenced prior context. DM confirmed.",wrong:"Access to decision moment could have been probed with a specific example."},
  {title:"AHW Digital // Moss",rep:"Jara",date:"2026-07-28",dur:"31m",path:"pm_direct",RAP:3,R:4,CB:4,ADM:3,CH:3,NS:3,score:3.5,outcome:"follow_up_agreed",well:"Good qualification. Multiple product areas explored. Feedback surfaced.",wrong:"Access to decision moment stated but not validated with a specific example."},
  {title:"Fabian Klett - Klett Consulting",rep:"Aurel",date:"2026-07-23",dur:"28m",path:"pm_direct",RAP:4,R:4,CB:4,ADM:4,CH:4,NS:4,score:4.0,outcome:"demo_booked",well:"All must-confirms covered. Access to decision moment confirmed with example. Demo booked.",wrong:"Nothing significant."},
  {title:"Ali Nada - GBC Gruppe",rep:"Aurel",date:"2026-07-23",dur:"51m",path:"pm_direct",RAP:4,R:4,CB:4,ADM:4,CH:4,NS:4,score:4.0,outcome:"demo_booked",well:"Excellent. Consulting firm with SMB clients. Full qualification. DM confirmed. Demo booked.",wrong:"Very long for a Discovery — some Demo overlap."},
  {title:"Voo Berlin / Nicolas",rep:"Aurel",date:"2026-07-27",dur:"23m",path:"pm_direct",RAP:3,R:3,CB:3,ADM:3,CH:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Procurement use case surfaced. Contact engaged.",wrong:"Client base not fully confirmed. Access to decision moment claimed but no example."},
  {title:"Deel x Moss Co-Selling",rep:"Jara",date:"2026-07-27",dur:"26m",path:"pm_direct",RAP:3,R:3,CB:3,ADM:3,CH:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Co-sell motion explored. Market overlap confirmed.",wrong:"Access to decision moment not validated. No demo booked."},
  {title:"Morlai Kargbo",rep:"Ezer",date:"2026-07-27",dur:"6m",path:"pa_handover",RAP:3,R:3,CB:3,ADM:3,CH:2,NS:3,score:2.9,outcome:"follow_up_agreed",well:"Relevant accounting contact. Good rapport. UK confirmed.",wrong:"Short. Champion not identified. No specific date."},
  {title:"Datavine intro",rep:"Ezer",date:"2026-07-23",dur:"29m",path:"pa_handover",RAP:3,R:3,CB:3,ADM:3,CH:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Good rapport. ERP integration angle. Contact engaged.",wrong:"Access to decision moment not probed with example."},
  {title:"Priya Raja-Motala",rep:"Ezer",date:"2026-07-23",dur:"9m",path:"pa_handover",RAP:3,R:3,CB:3,ADM:3,CH:2,NS:3,score:2.9,outcome:"follow_up_agreed",well:"Good discovery. Multiple product areas covered.",wrong:"Short. Champion not fully confirmed."},
  {title:"Rebecca Harvey",rep:"Ezer",date:"2026-07-22",dur:"10m",path:"pa_handover",RAP:3,R:3,CB:3,ADM:2,CH:2,NS:3,score:2.7,outcome:"follow_up_agreed",well:"UK accounting contact. Rapport established.",wrong:"Access to decision moment not explored. Champion not identified."},
  {title:"Ellie Dignam",rep:"Ezer",date:"2026-07-23",dur:"15m",path:"pa_handover",RAP:2,R:2,CB:2,ADM:2,CH:2,NS:2,score:2.0,outcome:"no_next_step",well:"Contact engaged. Multiple product areas.",wrong:"No prior context referenced. Access to decision moment not explored. No clear next step."},
  {title:"Blumberger / Nir",rep:"Jara",date:"2026-07-27",dur:"5m",path:"pm_direct",RAP:2,R:2,CB:2,ADM:2,CH:2,NS:2,score:2.0,outcome:"no_next_step",well:"Contact made.",wrong:"5 min. No qualification. No next step."},
  {title:"Falko Klamt / Deniz",rep:"Deniz",date:"2026-07-27",dur:"9m",path:"pm_direct",RAP:3,R:3,CB:3,ADM:3,CH:2,NS:3,score:2.9,outcome:"follow_up_agreed",well:"Good intro. Cards/reimbursements confirmed. Follow-up agreed.",wrong:"Champion not identified. Access to decision moment not validated."},
  {title:"finQuesto - Dirk",rep:"Niels",date:"2026-07-22",dur:"21m",path:"pm_direct",RAP:2,R:2,CB:2,ADM:2,CH:2,NS:2,score:2.0,outcome:"follow_up_agreed",well:"Long call. Multiple areas explored.",wrong:"Opening did not reference prior context. Access to decision moment not confirmed."},
  {title:"Kees FYBE Discovery",rep:"Niels",date:"2026-07-21",dur:"48m",path:"pm_direct",RAP:2,R:3,CB:3,ADM:2,CH:2,NS:2,score:2.4,outcome:"follow_up_agreed",well:"Long session. Product areas well covered.",wrong:"Rapport opening weak. Access to decision moment not validated. Next step vague."},
  {title:"Gerwin Koning Discovery",rep:"Niels",date:"2026-07-23",dur:"6m",path:"pm_direct",RAP:3,R:3,CB:3,ADM:2,CH:2,NS:3,score:2.7,outcome:"follow_up_agreed",well:"Good intro. Accounting context confirmed.",wrong:"Too short for full qualification. Access to decision moment not explored."},
  {title:"Odoo Experts - Erwin",rep:"Niels",date:"2026-07-28",dur:"19m",path:"pm_direct",RAP:2,R:2,CB:2,ADM:2,CH:2,NS:2,score:2.0,outcome:"no_next_step",well:"ERP integration angle relevant.",wrong:"Score 2/5 — qualification incomplete. No clear next step."},
  {title:"BePe Hamburg",rep:"Jara",date:"2026-07-21",dur:"13m",path:"pm_direct",RAP:1,R:1,CB:1,ADM:1,CH:1,NS:1,score:1.0,outcome:"no_next_step",well:"Contact present.",wrong:"No prior context. No qualification. No access to decision moment. No next step."},
  // ── Week 2: Jul 28 ──
  {title:"Fabian Gewald Discovery",rep:"Aurel",date:"2026-07-29",dur:"40m",path:"pm_direct",RAP:4,R:4,CB:4,ADM:4,CH:4,NS:4,score:4.0,outcome:"demo_booked",well:"Strong qualification. ADM confirmed with specific example. Priscilla as champion identified. Demo booked.",wrong:"Nothing significant."},
  {title:"AHW Digital W2",rep:"Jara",date:"2026-07-28",dur:"31m",path:"pm_direct",RAP:4,R:4,CB:4,ADM:3,CH:3,NS:3,score:3.5,outcome:"follow_up_agreed",well:"Good qualification. Product feedback surfaced. Multiple areas explored.",wrong:"ADM stated but not validated with specific example."},
  {title:"Tech Enable W2",rep:"Alex",date:"2026-07-28",dur:"25m",path:"pm_direct",RAP:4,R:4,CB:4,ADM:4,CH:3,NS:3,score:3.8,outcome:"follow_up_agreed",well:"Strong second discovery. Integration use case deepened. Prior context referenced.",wrong:"Champion not fully confirmed. Next step exploratory rather than demo."},
  {title:"NAS Conception",rep:"Aurel",date:"2026-07-29",dur:"27m",path:"pm_direct",RAP:3,R:3,CB:3,ADM:3,CH:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Tax advisory firm with SMB clients. Cards/reimbursements relevant. Follow-up agreed.",wrong:"ADM not validated with example. Champion not identified."},
  {title:"Finban x Moss",rep:"Jara",date:"2026-07-30",dur:"20m",path:"pm_direct",RAP:3,R:3,CB:3,ADM:3,CH:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Good rapport. Product feedback surfaced. Competitive intel gathered.",wrong:"ADM claimed but not validated. No demo booked."},
  {title:"Mike Wong",rep:"Alex",date:"2026-07-31",dur:"22m",path:"pm_direct",RAP:3,R:3,CB:3,ADM:3,CH:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"AI + intelligence angle explored. Multiple product areas relevant.",wrong:"ADM not probed with example. Champion not confirmed."},
  {title:"Odoo Experts W2",rep:"Niels",date:"2026-07-28",dur:"19m",path:"pm_direct",RAP:2,R:2,CB:2,ADM:2,CH:2,NS:2,score:2.0,outcome:"no_next_step",well:"ERP integration angle relevant.",wrong:"Qualification incomplete. ADM not explored. No clear next step."},
];

/* ══ DEMO — new criteria: TLR·REF·COM·OBJ·ENG·NS ══
   TLR=DemoRelevanceTailoring(w3) REF=ReferralMomentClarity(w3)
   COM=CommercialPartnershipModel(w2) OBJ=ObjectionConcernHandling(w2,null=N/A)
   ENG=PartnerEngagementReaction(w2) NS=NextStepActivation(w3) */
const DEMO = [
  {title:"FinAdvice Partner Demo",rep:"Alex",date:"2026-07-21",dur:"50m",TLR:4,REF:4,COM:4,OBJ:null,ENG:4,NS:4,score:4.0,outcome:"follow_up_agreed",well:"Tailored to Akos's client base. Referral moment discussed. Commercial covered. Strong engagement.",wrong:"Next step could have been a specific client intro, not just a follow-up call."},
  {title:"Ali Nada GBC - Demo",rep:"Aurel",date:"2026-07-23",dur:"51m",TLR:4,REF:4,COM:4,OBJ:3,ENG:4,NS:3,score:3.8,outcome:"follow_up_agreed",well:"Well tailored to consulting clients. Referral moment coached. Commercial covered.",wrong:"Next step soft — no specific client identified. Objection partially resolved."},
  {title:"Frank & Niels FYBE Demo",rep:"Niels",date:"2026-07-21",dur:"33m",TLR:4,REF:3,COM:3,OBJ:null,ENG:4,NS:3,score:3.5,outcome:"follow_up_agreed",well:"Tailored to FYBE client base. Frank actively engaged. Self-approval setting shown live.",wrong:"Referral moment not fully coached. Next step vague — no specific client intro."},
  {title:"finQuesto Demo",rep:"Niels",date:"2026-07-24",dur:"65m",TLR:4,REF:4,COM:3,OBJ:null,ENG:4,NS:4,score:3.9,outcome:"follow_up_agreed",well:"Thorough demo. All product areas covered for finQuesto client base. Partner engaged.",wrong:"Commercial model not fully proactive — answered questions but didn't lead."},
  {title:"Steuerwehr.at Demo",rep:"Aurel",date:"2026-07-21",dur:"53m",TLR:3,REF:3,COM:3,OBJ:null,ENG:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Long demo. Good product coverage.",wrong:"Tailoring surface-level. Referral moment not coached. Next step vague."},
  {title:"Pape & Co Advisor Portal",rep:"Nicola",date:"2026-07-28",dur:"75m",TLR:3,REF:3,COM:3,OBJ:3,ENG:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Product areas relevant. Partner engaged. Concerns addressed.",wrong:"Referral moment not explicitly coached. Long but next step soft."},
  {title:"Martijn FYBE Demo",rep:"Niels",date:"2026-07-23",dur:"19m",TLR:3,REF:3,COM:3,OBJ:null,ENG:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Good intro demo for new FYBE contact.",wrong:"Short. Referral moment not coached. Commercial not covered."},
  {title:"Happy Days MK Demo",rep:"Fred",date:"2026-07-24",dur:"45m",TLR:2,REF:2,COM:2,OBJ:null,ENG:2,NS:2,score:2.0,outcome:"no_next_step",well:"Long call. Multiple product areas shown.",wrong:"Not tailored. Referral moment not discussed. No commercial. No next step."},
  // ── Week 2: Jul 28 ──
  {title:"Blubooks Demo",rep:"Alex",date:"2026-07-30",dur:"33m",TLR:3,REF:3,COM:3,OBJ:null,ENG:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Product areas covered for bookkeeping clients. Engagement decent.",wrong:"Referral moment not explicitly coached. Commercial not proactively raised."},
  {title:"Benedikt Ebert BDU",rep:"Aurel",date:"2026-07-30",dur:"45m",TLR:3,REF:3,COM:3,OBJ:null,ENG:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Long session. Product areas relevant to consulting clients.",wrong:"Tailoring surface-level. Referral moment not coached."},
  {title:"Catalyst Demo",rep:"Jara",date:"2026-07-29",dur:"47m",TLR:3,REF:3,COM:3,OBJ:3,ENG:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Concerns addressed. Product areas covered. ERP integration angle explored.",wrong:"Referral moment not coached. Next step soft."},
  {title:"Pape & Co Demo W2",rep:"Nicola",date:"2026-07-28",dur:"75m",TLR:3,REF:3,COM:3,OBJ:3,ENG:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Long structured demo. Advisor portal angle. Partner engaged.",wrong:"Referral moment not explicitly coached. Next step vague."},
];

/* ══ MANAGEMENT — sub-typed ══
   subtype: "checkin" | "pipeline_review" | "product_enablement" | "qbr"
   
   CHECK-IN criteria: WRM·HLT·REF·NS
   WRM=RelationshipWarmth(w2) HLT=PartnerHealthCheck(w2) REF=ReferralSignal(w3) NS=NextStep(w3)
   
   PIPELINE REVIEW criteria: REFS·BLK·STALE·NEWREF·NS
   REFS=AllReferralsReviewed(w3) BLK=BlockersActioned(w3) STALE=StaleAddressed(w2) NEWREF=NewOpportunity(w2) NS=NextStep(w3)
   
   PRODUCT ENABLEMENT criteria: GAP·PRD·UND·RMC·NS
   GAP=KnowledgeGapConfirmed(w2) PRD=CorrectProductAreas(w3) UND=UnderstandingConfirmed(w3) RMC=ReferralMomentConnected(w2) NS=NextStep(w2)
   
   QBR criteria: PERF·WG·PLAN·COM·NS
   PERF=PerformanceVsTarget(w3) WG=WinsGaps(w2) PLAN=NextQuarterPlan(w3) COM=CommercialCommitment(w2) NS=NextStep(w3) */

const MANAGEMENT = [
  /* ── Check-ins ── */
  {title:"RSM Q&A",rep:"Fred",date:"2026-07-23",dur:"28m",subtype:"checkin",WRM:4,HLT:4,REF:4,NS:4,score:4.0,outcome:"follow_up_agreed",well:"Clear purpose. RSM team engaged. Questions well handled. Next meeting agreed.",wrong:"Nothing significant."},
  {title:"Jonathan Carling",rep:"Ezer",date:"2026-07-28",dur:"9m",subtype:"checkin",WRM:4,HLT:4,REF:4,NS:4,score:4.0,outcome:"follow_up_agreed",well:"Strong check-in with clear purpose. Referral signal surfaced. Specific next step.",wrong:"Nothing significant."},
  {title:"Wim Boer",rep:"Niels",date:"2026-07-28",dur:"5m",subtype:"checkin",WRM:4,HLT:3,REF:4,NS:3,score:3.5,outcome:"follow_up_agreed",well:"Competitive intel surfaced. Referral signal present. Good warmth.",wrong:"Next step vague — no date."},
  {title:"Fabian van der Schee",rep:"Niels",date:"2026-07-28",dur:"6m",subtype:"checkin",WRM:3,HLT:3,REF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Competitive intel. Check-in completed.",wrong:"No referral signal. Next step soft."},
  {title:"Liam Brandon",rep:"Niels",date:"2026-07-23",dur:"3m",subtype:"checkin",WRM:4,HLT:3,REF:3,NS:3,score:3.3,outcome:"follow_up_agreed",well:"Warm call. Good rapport. Follow-up agreed.",wrong:"Short. Referral signal not probed."},
  {title:"Rödl & Partner Monthly",rep:"Nicola",date:"2026-07-24",dur:"15m",subtype:"checkin",WRM:3,HLT:3,REF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Monthly cadence maintained. Bug flagged and acknowledged.",wrong:"No referral signal surfaced. Next step is next monthly — no specific action."},
  {title:"Gerko Geertsema",rep:"Niels",date:"2026-07-27",dur:"4m",subtype:"checkin",WRM:3,HLT:2,REF:3,NS:3,score:2.8,outcome:"follow_up_agreed",well:"Procurement use case mentioned. Follow-up agreed.",wrong:"Health check minimal. Referral not probed."},
  {title:"Leandro Binder",rep:"Aurel",date:"2026-07-24",dur:"6m",subtype:"checkin",WRM:3,HLT:3,REF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Good check-in. Cards area confirmed.",wrong:"No referral signal surfaced."},
  {title:"Kathrin Schulz",rep:"Jara",date:"2026-07-24",dur:"16m",subtype:"product_enablement",WRM:null,HLT:null,REF:null,NS:null,GAP:3,PRD:3,UND:3,RMC:3,NS2:3,score:3.0,outcome:"follow_up_agreed",well:"Product areas relevant to Kathrin's clients. Follow-up agreed.",wrong:"Knowledge gap not confirmed before starting. Referral moment not explicitly coached."},
  {title:"Royal Holloway x Moss",rep:"Jara",date:"2026-07-24",dur:"27m",subtype:"checkin",WRM:4,HLT:4,REF:3,NS:4,score:3.8,outcome:"follow_up_agreed",well:"Strong check-in. Commercial terms discussed. Multiple stakeholders present. Clear next step.",wrong:"Referral signal not explicitly probed."},
  {title:"Nael Jazeh",rep:"Deniz",date:"2026-07-28",dur:"6m",subtype:"checkin",WRM:3,HLT:2,REF:3,NS:3,score:2.8,outcome:"follow_up_agreed",well:"Cards area confirmed. Check-in completed.",wrong:"Health check minimal. No referral signal."},
  {title:"Ralf Meisel",rep:"Deniz",date:"2026-07-28",dur:"2m",subtype:"checkin",WRM:3,HLT:2,REF:2,NS:2,score:2.3,outcome:"follow_up_agreed",well:"Contact made.",wrong:"Very short. No health check. No referral signal."},
  {title:"Daniel Geiss",rep:"Deniz",date:"2026-07-28",dur:"4m",subtype:"checkin",WRM:3,HLT:3,REF:2,NS:3,score:2.8,outcome:"follow_up_agreed",well:"Good intro. Follow-up agreed.",wrong:"No referral signal probed."},
  {title:"Petra Radosztics",rep:"Deniz",date:"2026-07-28",dur:"3m",subtype:"checkin",WRM:3,HLT:2,REF:2,NS:2,score:2.3,outcome:"follow_up_agreed",well:"Contact made after multiple attempts.",wrong:"Short. No health check depth. No referral signal."},
  {title:"Aurel BT Consulting",rep:"Aurel",date:"2026-07-22",dur:"24m",subtype:"checkin",WRM:2,HLT:2,REF:2,NS:2,score:2.0,outcome:"no_next_step",well:"Pilot customer concept agreed in principle.",wrong:"No purpose. No specific next step. Ended with vague expectation of future updates."},
  {title:"Wencke Mazars",rep:"Niels",date:"2026-07-22",dur:"16m",subtype:"checkin",WRM:2,HLT:2,REF:2,NS:2,score:2.0,outcome:"no_next_step",well:"Existing relationship maintained.",wrong:"No clear purpose. No referral signal. No next step."},
  {title:"Yori May",rep:"Niels",date:"2026-07-22",dur:"11m",subtype:"checkin",WRM:2,HLT:2,REF:2,NS:2,score:2.0,outcome:"no_next_step",well:"Contact maintained.",wrong:"No purpose stated. No referral signal. No next step."},
  {title:"Ted Jansen",rep:"Niels",date:"2026-07-21",dur:"4m",subtype:"checkin",WRM:2,HLT:2,REF:2,NS:2,score:2.0,outcome:"no_next_step",well:"Brief contact.",wrong:"Too short. No purpose. No next step."},
  {title:"awicontax Viktor",rep:"Nicola",date:"2026-07-28",dur:"3m",subtype:"checkin",WRM:1,HLT:1,REF:1,NS:1,score:1.0,outcome:"no_next_step",well:"Contact made.",wrong:"2.6 min. No purpose. No health check. No referral signal. No next step."},
  {title:"Mastercard Bi-weekly",rep:"Jara",date:"2026-07-21",dur:"34m",subtype:"checkin",WRM:1,HLT:1,REF:1,NS:1,score:1.0,outcome:"no_next_step",well:"Attendees present.",wrong:"No purpose for this specific call. No referral signal. No next step."},
  {title:"Rob Droppers",rep:"Niels",date:"2026-07-22",dur:"5m",subtype:"checkin",WRM:1,HLT:1,REF:1,NS:1,score:1.0,outcome:"no_next_step",well:"Warm contact.",wrong:"Preparation gap — contact details wrong. No clear purpose. No next step."},
  {title:"Dr Manthey",rep:"Aurel",date:"2026-07-21",dur:"6m",subtype:"checkin",WRM:1,HLT:1,REF:1,NS:1,score:1.0,outcome:"no_next_step",well:"Contact made.",wrong:"No purpose. No health check. No next step."},
  {title:"Henk Dijkhuizen",rep:"Niels",date:"2026-07-21",dur:"13m",subtype:"checkin",WRM:2,HLT:2,REF:2,NS:2,score:2.0,outcome:"no_next_step",well:"Accounting integrations context.",wrong:"No purpose. No referral signal. No next step."},
  {title:"Julie Christiani",rep:"Deniz",date:"2026-07-22",dur:"3m",subtype:"checkin",WRM:1,HLT:1,REF:1,NS:1,score:1.0,outcome:"no_next_step",well:"Contact made.",wrong:"No purpose. No health check. No next step."},
  /* ── Pipeline Reviews ── */
  {title:"Mathijs Bakker Pipeline",rep:"Niels",date:"2026-07-27",dur:"10m",subtype:"pipeline_review",REFS:4,BLK:4,STALE:3,NEWREF:4,NS:4,score:3.8,outcome:"follow_up_agreed",well:"Referrals reviewed by name. Blockers actioned. New opportunity surfaced. Clear next step.",wrong:"Stale referrals not fully addressed proactively — reactive rather than proactive."},
  /* ── Product Enablement ── */
  {title:"Kees FYBE Enablement",rep:"Niels",date:"2026-07-27",dur:"74m",subtype:"product_enablement",GAP:4,PRD:4,UND:4,RMC:4,NS2:4,score:4.0,outcome:"follow_up_agreed",well:"74 min. All product areas covered for FYBE client base. Understanding confirmed. Referral moment connected.",wrong:"Nothing significant. Thorough session."},
  {title:"Peter FYBE Enablement",rep:"Niels",date:"2026-07-28",dur:"26m",subtype:"product_enablement",GAP:3,PRD:4,UND:3,RMC:3,NS2:4,score:3.4,outcome:"follow_up_agreed",well:"Product areas relevant. Next step specific.",wrong:"Knowledge gap not confirmed upfront. Understanding check surface-level."},
  {title:"Mick Billy Grace",rep:"Niels",date:"2026-07-24",dur:"22m",subtype:"product_enablement",GAP:3,PRD:3,UND:3,RMC:3,NS2:3,score:3.0,outcome:"follow_up_agreed",well:"Product context maintained for Billy Grace.",wrong:"Generic elements. Referral moment not explicitly coached."},
  {title:"Poool x Moss",rep:"Jara",date:"2026-07-28",dur:"25m",subtype:"product_enablement",GAP:3,PRD:3,UND:3,RMC:3,NS2:3,score:3.0,outcome:"follow_up_agreed",well:"Cards and ERP use cases relevant. Bug surfaced and acknowledged.",wrong:"Knowledge gap not confirmed. Referral moment not connected."},
  /* ── Check-ins continued ── */
  {title:"GreenStones Continued",rep:"Jara",date:"2026-07-21",dur:"22m",subtype:"checkin",WRM:2,HLT:2,REF:2,NS:2,score:2.0,outcome:"no_next_step",well:"Existing relationship. Product feedback captured.",wrong:"No clear purpose. Bugs discussed but no referral signal or next step."},
  {title:"Catalyst x Moss",rep:"Jara",date:"2026-07-21",dur:"30m",subtype:"checkin",WRM:3,HLT:3,REF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Commercial model discussed. Internal advocates identified.",wrong:"Next step not fully locked. Commercial decision deferred."},
  {title:"Billy Grace Next Steps",rep:"Niels",date:"2026-07-21",dur:"24m",subtype:"checkin",WRM:2,HLT:2,REF:2,NS:2,score:2.0,outcome:"no_next_step",well:"Relationship maintained.",wrong:"No purpose. No referral signal. No next step."},
  {title:"Pape & Co Monthly",rep:"Nicola",date:"2026-07-21",dur:"24m",subtype:"checkin",WRM:2,HLT:2,REF:2,NS:2,score:2.0,outcome:"no_next_step",well:"Monthly cadence maintained. Product feedback.",wrong:"No referral signal. No specific next step."},
  {title:"Sebastian Haidn",rep:"Deniz",date:"2026-07-28",dur:"10m",subtype:"checkin",WRM:3,HLT:2,REF:2,NS:2,score:2.3,outcome:"follow_up_agreed",well:"Contact made.",wrong:"Gatekeeper dynamic. No referral signal. No specific next step."},
  {title:"Dirk Seeger",rep:"Deniz",date:"2026-07-28",dur:"3m",subtype:"checkin",WRM:2,HLT:1,REF:1,NS:1,score:1.3,outcome:"no_next_step",well:"Contact attempted.",wrong:"Gatekeeper. No meaningful conversation."},
  // ── Week 2: Jul 28 ──
  {title:"Greyt & Moss - Bert",rep:"Niels",date:"2026-07-31",dur:"33m",subtype:"product_enablement",GAP:5,PRD:5,UND:5,RMC:5,NS2:5,score:5.0,outcome:"follow_up_agreed",well:"Exceptional 33-min enablement. All product areas covered. Understanding confirmed. Referral moment explicitly coached. Specific next step.",wrong:"Nothing significant."},
  {title:"Praevo Partners",rep:"Fred",date:"2026-07-31",dur:"54m",subtype:"product_enablement",GAP:4,PRD:4,UND:4,RMC:4,NS2:4,score:4.0,outcome:"follow_up_agreed",well:"Thorough 54-min enablement. Product areas well covered. Understanding confirmed. Ezer present as well.",wrong:"Knowledge gap not fully confirmed upfront."},
  {title:"4PointZero Enablement",rep:"Jara",date:"2026-07-29",dur:"35m",subtype:"product_enablement",GAP:4,PRD:4,UND:4,RMC:4,NS2:4,score:4.0,outcome:"follow_up_agreed",well:"All product areas covered. Referral moment connected. Competitive intel gathered.",wrong:"Knowledge gap not explicitly confirmed before starting."},
  {title:"Büsra Ecovis",rep:"Nicola",date:"2026-07-29",dur:"14m",subtype:"product_enablement",GAP:4,PRD:4,UND:4,RMC:4,NS2:4,score:4.0,outcome:"follow_up_agreed",well:"Accounting integrations relevant to Ecovis. Understanding confirmed. Specific next step.",wrong:"Nothing significant."},
  {title:"Peter FYBE W2",rep:"Niels",date:"2026-07-28",dur:"26m",subtype:"product_enablement",GAP:3,PRD:4,UND:3,RMC:4,NS2:4,score:3.8,outcome:"follow_up_agreed",well:"Product areas relevant. Referral moment connected. Specific next step.",wrong:"Knowledge gap not confirmed upfront."},
  {title:"Moore TK Pipeline",rep:"Nicola",date:"2026-07-30",dur:"28m",subtype:"pipeline_review",REFS:4,BLK:4,STALE:3,NEWREF:4,NS:4,score:3.8,outcome:"follow_up_agreed",well:"Referrals reviewed by name. Blockers actioned. New opportunity surfaced. Clear next step.",wrong:"Stale referrals reactive rather than proactive."},
  {title:"NA Media Pipeline",rep:"Jara",date:"2026-07-31",dur:"10m",subtype:"pipeline_review",REFS:3,BLK:3,STALE:3,NEWREF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Pipeline reviewed. Follow-up agreed.",wrong:"Short. Not all referrals reviewed systematically."},
  {title:"Dave YourFirst Pipeline",rep:"Niels",date:"2026-07-30",dur:"17m",subtype:"pipeline_review",REFS:3,BLK:3,STALE:3,NEWREF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Pipeline covered. Referrals discussed.",wrong:"Not fully systematic. Stale referrals not proactively raised."},
  {title:"Anneleen VAR",rep:"Niels",date:"2026-07-30",dur:"13m",subtype:"checkin",WRM:4,HLT:4,REF:4,NS:4,score:4.0,outcome:"follow_up_agreed",well:"Clear purpose. Partner health surfaced. Referral signal present. Specific next step.",wrong:"Nothing significant."},
  {title:"Johan van Rest",rep:"Niels",date:"2026-07-30",dur:"7m",subtype:"checkin",WRM:4,HLT:4,REF:4,NS:4,score:4.0,outcome:"follow_up_agreed",well:"Warm call. Referral signal surfaced. Next step agreed.",wrong:"Nothing significant."},
  {title:"Daan Krosse",rep:"Niels",date:"2026-07-30",dur:"4m",subtype:"checkin",WRM:4,HLT:3,REF:4,NS:4,score:3.8,outcome:"follow_up_agreed",well:"Short but purposeful. Cards area confirmed. Referral signal. Next step.",wrong:"Health check brief."},
  {title:"Ted Embora",rep:"Niels",date:"2026-07-29",dur:"11m",subtype:"checkin",WRM:4,HLT:3,REF:4,NS:4,score:3.8,outcome:"follow_up_agreed",well:"Purpose clear. Referral signal — Embora client in scope. Specific next step.",wrong:"Health check brief."},
  {title:"Sabine Sommerfeldt",rep:"Deniz",date:"2026-07-30",dur:"8m",subtype:"checkin",WRM:4,HLT:4,REF:4,NS:4,score:4.0,outcome:"follow_up_agreed",well:"Clear purpose. Partner health probed. Referral signal surfaced. Specific next step.",wrong:"Nothing significant."},
  {title:"Poool Next Steps",rep:"Jara",date:"2026-07-31",dur:"15m",subtype:"product_enablement",GAP:3,PRD:3,UND:3,RMC:3,NS2:3,score:3.0,outcome:"follow_up_agreed",well:"ERP use case covered. Product feedback gathered.",wrong:"Knowledge gap not confirmed. Referral moment not connected."},
  {title:"Lars Nijkerk",rep:"Niels",date:"2026-07-29",dur:"5m",subtype:"checkin",WRM:3,HLT:3,REF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Competitive intel surfaced. Check-in completed.",wrong:"No referral signal. Next step soft."},
  {title:"Bert van der Meer",rep:"Niels",date:"2026-07-29",dur:"1m",subtype:"checkin",WRM:3,HLT:2,REF:2,NS:2,score:2.5,outcome:"no_next_step",well:"Brief contact made.",wrong:"Too short. No referral signal. No next step."},
  {title:"Wim Boer W2",rep:"Niels",date:"2026-07-28",dur:"5m",subtype:"checkin",WRM:4,HLT:3,REF:3,NS:3,score:3.3,outcome:"follow_up_agreed",well:"Competitive intel. Referral signal present. Follow-up agreed.",wrong:"Next step vague — no date."},
  {title:"Fabian van der Schee W2",rep:"Niels",date:"2026-07-28",dur:"6m",subtype:"checkin",WRM:3,HLT:3,REF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Check-in completed. Cards context confirmed.",wrong:"No referral signal. Next step soft."},
  {title:"Dirk finQuesto W2",rep:"Niels",date:"2026-07-28",dur:"17m",subtype:"checkin",WRM:3,HLT:3,REF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Competitive intel gathered. Product feedback. Check-in completed.",wrong:"Referral signal not probed. Next step not specific."},
  {title:"awicontax Viktor W2",rep:"Nicola",date:"2026-07-28",dur:"3m",subtype:"checkin",WRM:2,HLT:1,REF:1,NS:1,score:2.0,outcome:"no_next_step",well:"Contact made.",wrong:"No purpose again. No health check. No referral signal. No next step. Second consecutive week."},
  {title:"Jan Niemeyer W2",rep:"Deniz",date:"2026-07-29",dur:"5m",subtype:"checkin",WRM:3,HLT:3,REF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Cards context confirmed. Check-in completed.",wrong:"No referral signal. Next step soft."},
  {title:"Nael Jazeh W2",rep:"Deniz",date:"2026-07-28",dur:"6m",subtype:"checkin",WRM:3,HLT:3,REF:3,NS:3,score:3.0,outcome:"follow_up_agreed",well:"Cards area confirmed. Follow-up agreed.",wrong:"Health check minimal. No referral signal."},
  {title:"Ralf Meisel W2",rep:"Deniz",date:"2026-07-28",dur:"2m",subtype:"checkin",WRM:3,HLT:2,REF:2,NS:2,score:2.5,outcome:"follow_up_agreed",well:"Contact maintained.",wrong:"Very short. No health check depth. No referral signal."},
  {title:"Daniel Geiss W2",rep:"Deniz",date:"2026-07-28",dur:"4m",subtype:"checkin",WRM:3,HLT:3,REF:2,NS:3,score:2.8,outcome:"follow_up_agreed",well:"Good intro. Follow-up agreed.",wrong:"No referral signal probed."},
  {title:"Petra Radosztics W2",rep:"Deniz",date:"2026-07-28",dur:"3m",subtype:"checkin",WRM:3,HLT:2,REF:2,NS:2,score:2.3,outcome:"follow_up_agreed",well:"Contact made.",wrong:"Short. No health check depth. No referral signal."},
  {title:"Sebastian Haidn W2",rep:"Deniz",date:"2026-07-28",dur:"10m",subtype:"checkin",WRM:3,HLT:2,REF:2,NS:2,score:2.5,outcome:"follow_up_agreed",well:"Contact maintained.",wrong:"Gatekeeper dynamic. No referral signal."},
  {title:"Dirk Seeger W2",rep:"Deniz",date:"2026-07-28",dur:"3m",subtype:"checkin",WRM:2,HLT:1,REF:1,NS:1,score:2.0,outcome:"no_next_step",well:"Contact attempted.",wrong:"Gatekeeper. No substance."},
  {title:"Darron Enablement",rep:"Niels",date:"2026-07-29",dur:"5m",subtype:"product_enablement",GAP:3,PRD:3,UND:3,RMC:3,NS2:3,score:3.0,outcome:"follow_up_agreed",well:"Cards area relevant. Check-in completed.",wrong:"Short. Referral moment not coached."},
  {title:"Joeri van Zijp",rep:"Niels",date:"2026-07-29",dur:"5m",subtype:"product_enablement",GAP:3,PRD:3,UND:3,RMC:3,NS2:3,score:3.0,outcome:"follow_up_agreed",well:"Cards area relevant.",wrong:"Short. Knowledge gap not confirmed. Referral moment not coached."},
];

/* ══ PIPELINE ══ */
/* ══ PIPELINE = {
  funnel: {
    DE: { sourced: 18, discovery: 9, demo: 6 },
    GB: { sourced: 28, discovery: 8, demo: 5 },
    NL: { sourced: 16, discovery: 10, demo: 5 },
    AT: { sourced: 7,  discovery: 4, demo: 3 },
  },
  q3_targets: {
    DE: { sqls: 18, arr: 45000 },
    GB: { sqls: 12, arr: 30000 },
    NL: { sqls: 15, arr: 38000 },
    AT: { sqls: 8,  arr: 20000 },
  }
};
